external:
  task:
    url: http://localhost:50000
    read-timeout-millis: 3000
    connect-timeout-millis: 3000
  user:
    url: http://localhost:50001
    read-timeout-millis: 3000
    connect-timeout-millis: 3000

logging:
  file:
    name: logs/myapp.log
