name: Build

#############################
# Start the job on all push #
#############################
on: push
# on:
#   push:
#     branches-ignore: [master]
#     # Remove the line above to run when pushing to master
#   pull_request:
#     branches: [master]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Build by Gradle
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      ################################
      # Run Build                    #
      ################################
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew build

      ################################
      # Run UnitTest                 #
      ################################
      - name: Build with Gradle
        run: ./gradlew test


  lint:
    # Name the Job
    name: Lint
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_KOTLIN: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
