name: CI

#############################
# Start the job on all push #
#############################
on: push
# on:
#   push:
#     branches-ignore: [master]
#     # Remove the line above to run when pushing to master
#   pull_request:
#     branches: [master]

################
# Set the Jobs #
################
jobs:

  #################
  # Set build Job #
  #################
  build:
    # Name the Job
    name: Build by Gradle
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      ################################
      # Run Build                    #
      ################################
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Build with Gradle
        run: ./gradlew build jacocoTestReport
      - name: Archive unit test results
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-report
          path: build/reports/tests/test
      - name: Archive coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: build/reports/jacoco/test/html
 
  #################
  # Set Lint Job #
  #################
  lint:
    # Name the Job
    name: Lint
    # Set the agent to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_KOTLIN: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
